name: Build & Staging Deploy
on:
  push:
    branches:
      - draft_decorators
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Generate
        run: npm run deploy

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build